### ISSUE TITLE
incomplete dependencies?

### ISSUE THREAD

**Issue by phavx** [glu10/trough#1]
First hi and thanks, found this via google on the search for a better replacement for liferea, maybe it's it.

But for me to try it, I gotta need it to run first, but

> python3.4 ./trough.py 
Traceback (most recent call last):
  File "./trough.py", line 61, in set_window_icon
    icon = theme.lookup_icon("rss", 32, Gtk.IconLookupFlags.GENERIC_FALLBACK).load_icon()
 AttributeError: 'NoneType' object has no attribute 'load_icon'
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
 > File "./trough.py", line 156, in <module>
    trough = Trough()
  File "./trough.py", line 36, in __init__
    self.set_window_icon()
  File "./trough.py", line 63, in set_window_icon
    except GLib.Gerror:
  File "/usr/lib64/python3.4/site-packages/gi/overrides/__init__.py", line 38, in __getattr__
[~/trough][hikaru]                                                                                                                                     [23:18]G
  File "/usr/lib64/python3.4/site-packages/gi/module.py", line 137, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.GLib' object has no attribute 'Gerror'

is what I get on a Gentoo ~amd64 system with the listed dependencies installed.

Python isn't my strong side, so I'd be happy for some help finding the problem here, thanks.

**Comment by glu10** [comment]
Hey Phavx, thanks for opening the issue.

That looks like it was just my shoddy error checking, the lookup_icon() call can return None if it doesn't find an RSS icon in your theme. I'll fix it in a commit tomorrow. The AttributeError in the end is interesting though, are you on GTK+ 3? You're right in that I should be more explicit about that dependency if you're not, I didn't list it yet because I wasn't sure with how compatible things would end up being. For reference, I'm on 3.18.2 on Arch.

Even with the fix, there are probably going to be a ton of other problems because I never expected anyone else to try to run this yet, you caught my free time project about two weekends in.

Liferea is definitely going to be better than this at the moment.  If you're still interested, check back around late December and things should be looking way better.

You may want to delete ~/.config/trough/ since it may be useless clutter to you right now if the script created it before crashing.

**Comment by phavx** [comment]
Thanks for your reply.

> The AttributeError in the end is interesting though, are you on GTK+ 3?

I have gtk+3 installed, version 3.16.7 currently from Gentoo's portage build with these USE-flags
> X cups introspection -aqua -broadway -cloudprint -colord -debug -examples -test -vim-syntax -wayland -xinerama

As I'm not running GNOME or XFCE but just a plain WM (FVWM in my case), maybe a dependency is missing which would have been pulled with full on GNOME.

> Even with the fix, there are probably going to be a ton of other problems because I never expected anyone else to try to run this yet, you caught my free time project about two weekends in.

No worries, all good from my side :) I'm currently just using my own which is even simpler, but it works (no offense) (https://github.com/phavx/nasap in case you're interested).

Glad to help out according to my abilities, so let me know if I can do something.

**Comment by glu10** [comment]
Latest commit should have fixed both problems, the AttributeError was just a capitalization problem I didn't notice before, oops.

> I'm currently just using my own which is even simpler, but it works (no offense) (https://github.com/phavx/nasap in case you're interested)

None taken, your five line header in that project is a thing of beauty. At first I was thinking about making something that exported to PDF and had a newspaper-like format, but the formatting would have probably been a nightmare.

I uploaded a screenshot in case something still doesn't work for you: https://i.imgur.com/7rQgBUi.png?1

**Comment by phavx** [comment]
> python3 ./trough.py
/usr/lib64/python3.4/site-packages/gi/overrides/Gtk.py:567: Warning: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.add_button(text, response)

This is currently what I get when launching the application, "just" a warning, but application comes up successfully.

However, trying to add any feed (tried 4 so far), I get

>Traceback (most recent call last):
  File "./trough.py", line 119, in on_add_clicked
    response == Gtk.ResponseType.OK and dialog.add_entry(self.config))):
  File "/home/phavx/trough/addFeed.py", line 66, in add_entry
    feedparser.parse(uri)
  File "/usr/lib64/python3.4/site-packages/feedparser.py", line 3944, in parse
    saxparser.parse(source)
  File "/usr/lib64/python3.4/site-packages/drv_libxml2.py", line 190, in parse
    _d(reader.LocalName()))
  File "/usr/lib64/python3.4/site-packages/drv_libxml2.py", line 70, in _d
    return _decoder(s)[0]
  File "/usr/lib64/python3.4/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: 'str' does not support the buffer interface

From your provided screenshots it seem it could be something for me once it's running as it should :)

**Comment by glu10** [comment]
The button warning I can take care of.

> File "/usr/lib64/python3.4/encodings/utf_8.py", line 16, in decode
return codecs.utf_8_decode(input, errors, True)
TypeError: 'str' does not support the buffer interface

This problem, unfortunately, seems to be a problem with feedparser itself. There are two open issues [here](https://github.com/kurtmckee/feedparser/issues/30) and [here](https://github.com/richardpetithory/feedparser/issues/432).

That initially didn't make sense to me because you had used feedparser in your own project, but you did it in Python 2 and not 3. I saw instances of the issue with 3.3-3.4.

Can you try to modify the addFeed.py with the code found [here](http://blog.yjl.im/2013/12/workaround-of-libxml2-unsupported.html) to see if it works for you?

If that doesn't work, you could try upgrading to python 3.5, that's just a wild guess though, and from a quick look it still seems like that's still in testing on Gentoo.

You can quickly try to recreate the bug by just doing:
```shell
python3
import feedparser
feedparser.parse('http://rss.cnn.com/rss/cnn_topstories.rss')
```

**Comment by phavx** [comment]
I tried modifying the addFeed.py as described, the error thrown above no longer gets listed (good), instead I get

> KeyError: 'description'
Traceback (most recent call last):
  File "./trough.py", line 124, in on_add_clicked
    self.on_refresh_clicked(None)
  File "./trough.py", line 130, in on_refresh_clicked
    self.current_view().refresh(self.gatherer.collect())
  File "/home/avx/trough/gatherer.py", line 54, in collect
    item = Item(label, entry['title'], self.description_cleanup(entry['description']), entry['link'])
  File "/usr/lib64/python3.4/site-packages/feedparser.py", line 349, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'description'
Traceback (most recent call last):
  File "./trough.py", line 130, in on_refresh_clicked
    self.current_view().refresh(self.gatherer.collect())
  File "/home/avx/trough/gatherer.py", line 54, in collect
    item = Item(label, entry['title'], self.description_cleanup(entry['description']), entry['link'])
  File "/usr/lib64/python3.4/site-packages/feedparser.py", line 349, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'description'

As for your "quick test", yes it works in python 2.7, it breaks with python 3.4.

As for python3.5, I got it installed, I'm currently fighting with it to get feedparser installed for that specific version so can't give an answer for that, yet.

**Comment by glu10** [comment]
> File "/usr/lib64/python3.4/site-packages/feedparser.py", line 349, in getitem
return dict.getitem(self, key)
KeyError: 'description'

Feedparser probably didn't actually parse the RSS feed correctly. If you tried to print the result of the parse you'd probably get something like

`{'bozo': 1, 'bozo_exception': SAXParseException('not well-formed (invalid token)',), 'namespaces': {}, 'feed': {}, 'version': '', 'entries': [], 'encoding': 'utf-8'}`

If you got something else, like some valid feed information, that would be interesting.

You can just run this to see:
```
python3
import feedparser
feedparser.PREFERRED_XML_PARSERS.remove('drv_libxml2')
p = feedparser.parse('http://rss.cnn.com/rss/cnn_topstories.rss')
p[0]
p[0]['description']
```

I probably should be double checking for the case of the description not being there though, but that's not a problem with the CNN feed.


> As for python3.5, I got it installed, I'm currently fighting with it to get feedparser installed for that specific version so can't give an answer for that, yet.

Does the following command work?
```
python3.5 -m pip install feedparser
```


I'm sorry you're having so much frustration with this, I had no idea that feedparser was so finicky. If it becomes too much of a hassle for you I understand.

**Comment by phavx** [comment]
Aha, found the "culprit", the feed I'm using is http://blog.fefe.de/rss.xml. That feed is certainly unusual, but I think it's not "illegal" to format it like this.

As for
> python3.5 -m pip install feedparser

that's basically a catch-22, need to get pip installed for 3.5 first. I'm on it, should have some time for that stuff on the weekend I hope.

It's a little annoying, yes, but probably still faster than me learning to do GUI applications ;)

**Comment by glu10** [comment]
Well hopefully this is the end of it!

I just tested a fix on 3.4 and it works, see if it does for you. Hopefully this saves you from the 3.5 headache.

**Comment by phavx** [comment]
Sorry, took a while longer :/

> python3.4 trough.py 
/usr/lib64/python3.4/site-packages/gi/overrides/Gtk.py:567: Warning: The property GtkButton:use-stock is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.add_button(text, response)
/usr/lib64/python3.4/site-packages/gi/overrides/Gtk.py:567: Warning: The property GtkSettings:gtk-button-images is deprecated and shouldn't be used anymore. It will be removed in a future version.
  self.add_button(text, response)
Traceback (most recent call last):
  File "/home/avx/trough/addFeed.py", line 66, in add_entry
    feedparser.parse(uri)  # This call is purely to try to catch problems before the feed is added.
  File "/usr/lib64/python3.4/site-packages/feedparser.py", line 3944, in parse
    saxparser.parse(source)
  File "/usr/lib64/python3.4/site-packages/drv_libxml2.py", line 190, in parse
    _d(reader.LocalName()))
  File "/usr/lib64/python3.4/site-packages/drv_libxml2.py", line 70, in _d
    return _decoder(s)[0]
  File "/usr/lib64/python3.4/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: 'str' does not support the buffer interface

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
  File "trough.py", line 119, in on_add_clicked
    response == Gtk.ResponseType.OK and dialog.add_entry(self.config))):
  File "/home/avx/trough/addFeed.py", line 68, in add_entry
    if feedparser.PREFERRED_XML_PARSERS.contains('drv_libxml2'):
AttributeError: 'list' object has no attribute 'contains'

Still get this after pulling latest changes, clearing ~/.config/trough and trying with the feed mentioned above.

**Comment by glu10** [comment]
Sorry for the radio silence, the world doesn't want me to have free time right now.

That was Java programming leaking into my mind in a weird way when I made a quick change. It should have just been
```
if 'drv_libxml2' in feedparser.PREFERRED_XML_PARSERS
```
and not
```
if feedparser.PREFERRED_XML_PARSERS.contains('drv_libxml2')
```
because .contains() doesn't exist at all. Incredibly silly mistake, I committed the fix. What's strange is that means the test I did on 3.4 didn't throw the exception related to drv_libxml2, but let's avoid going back into that rabbit hole for now because it shouldn't be a concern anymore.

I'm going to ramp up the development on Trough in early December when I'll have significantly more time, so big improvements will be arriving then :) Again, I apologize for all the small bugs you're running into.

Is there any feature that you'd like to see in the future?

**Comment by phavx** [comment]
Good news, with the latest fix, the feed loads properly and no crash so far - but it's also the only one I tested so far. Thanks for staying on it.

As for features, there are some things I could think of and I'd create some seperate issues for that, but to judge that, it would help to get a little "vision statement" of your plans first(doesn't make sense to wish for something which might never come ;))

**Comment by glu10** [comment]
My main goal is being really lightweight, especially visually. I want to reduce the pain of answering "what is going on right now?" so that a user can quickly decide if they are actually interested in something or not, and if they are they can just hop on their browser. If what they care about is purely text-based then they may not even need the browser at all, and this could spare them the pain of having to process unnecessary visual information. Given that, I have no plans to render HTML or trying to emulate the full browser experience in any way. If you wanted something more like that, maybe check out [this project](https://jangernert.github.io/feedreader/) because it seems to have a lot of features, but most just don't appeal to me because I don't really use any of those services that it integrates with.

I'm also okay with assuming a more advanced user. I want to build something that people can easily morph into what they want, rather than trying to build something that does too much for them that they don't need.

**Comment by phavx** [comment]
Perfectly fine answer for my needs, I'm not interested in fancy either, just in speed & content mostly.

I'll go ahead and file some issues with ideas/wishes I'm having, regarding all of them: I'm perfectly fine having to modify a config file by hand for the stuff, no need (from my pov) to create GUI config dialogs for that.

**Comment by glu10** [comment]
Thanks for the ideas, I'll look into implementing both of them when I get back into the swing of things. I probably will do a GUI for the settings, there are widgets like GtkFontChooser that actually save a lot work. The single/double/triple view change I was envisioning working like Evince's single/dual view, where you can just choose it quickly from the hamburger menu and the decision sticks between sessions.
